<iframe id="<?php echo $this->getFrameId(); ?>" src="<?php echo $this->getSubmitterUrl(); ?>" frameborder="0" width="100%" height="787px"></iframe>
<script type="text/javascript">
    document.observe("dom:loaded", function () {
        varienGlobalEvents.attachEventHandler("showTab", function (event) {
            if (event.tab.name == "<?php echo $this->getTabName(); ?>") {
                var frame = $('<?php echo $this->getFrameId(); ?>');
                frame.src = frame.src; // Reload frame
            }
        });
    });
</script>
